### ISSUE TITLE
Storing the feature value corresponding to the MAX ECR

### ISSUE THREAD

**Issue by bhushan9** [bhushan9/CSC591-Machine-Learning#10]
I created a new variable store_df and added the kmeans.labels_ values to the dataframe in the condition where we check for max ecr and the else part of if unique >5 .  However this approach only seems to add a single column and each at each iteration of for loop it replaces the existing column.

**Comment by zsthampi** [comment]
numpy.array is the way to go. 

x = numpy.array([[1,2,3],[4,5,6],[7,8,9]]) 
x[2][2] 
------- 9

**Comment by bhushan9** [comment]
Issue solved using deepcopy() method.
